name: "Build"
on:
  pull_request:
    paths-ignore:
      - '.txt'
      - '*.MD'
      - '*.md'
      - 'LICENSE'
      - 'docs/**'
  push:
    branches:
      - master
      - develop
      - release/*
    tags-ignore:
      - '*'
    paths-ignore:
      - '.txt'
      - '*.MD'
      - '*.md'
      - 'LICENSE'
      - 'docs/**'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java: [15]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
          architecture: x64
      - name: Cache Maven packages
        uses: actions/cache@v2.1.5
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: mvn clean install

  notify-slack:
    if: github.event_name == 'push' && (success() || failure())
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: "Slack workflow notification"
        uses: Gamesight/slack-workflow-status@master
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          slack_webhook_url: ${{secrets.SLACK_WEBHOOK_URL}}
          
      - name: Start Fortify-SAST
        uses: actions/checkout@v2
        with:
        # Fetch at least the immediate parents so that if this is a pull request then we can checkout the head.
          fetch-depth: 2
        # If this run was triggered by a pull request event, then checkout the head of the pull request instead of the merge commit.
      - run: git checkout HEAD^2
        if: ${{ github.event_name == 'pull_request' }} 

    # Java is required to run ScanCentral Client, and may be required for your build
    # Java version to use depends on the Java version required to run your build (if any),
    # and the Java version supported by the ScanCentral Client version that you are running
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

    ### Set up Fortify ScanCentral Client ###
      - name: Download Fortify ScanCentral Client
        uses: fortify/gha-setup-scancentral-client@v1   
        with:
          version: 21.2.2                                      # On-prem customers should specify a client version that matches their ScanCentral environment
                                                             # FoD customers usually should not specify a version but rather rely on the default version
          client-auth-token: ${{ secrets.CLIENT_AUTH_TOKEN }}  # Optional, but required if ScanCentral Controller requires client authentication

    ### Run Fortify ScanCentral Client ###
    # Update BUILD_OPTS based on the ScanCentral Client documentation and your project's included tech stack(s).
    #   ScanCentral Client will download dependencies for maven, gradle and msbuild projects.
    #   For other build tools, add your build commands to the workflow to download necessary dependencies and prepare according to Fortify SCA documentation.
      - name: Setting FQDN address
        run: |
            export RUNNER_ALLOW_RUNASROOT="1"
            export AGENT_ALLOW_RUNASROOT="1"
            sudo echo "54.198.22.254 fortify.cyberxdemo.com" | sudo tee -a /etc/hosts
      - name: Perform SAST Scan
        run: scancentral -url ${SC_CONTROLLER_URL} start $BUILD_OPTS -upload -application $APPLICATION -version $VERSION -uptoken $SSC_UPLOAD_TOKEN
        env:
          SC_CONTROLLER_URL: ${{ secrets.SC_CONTROLLER_URL }}
          SSC_UPLOAD_TOKEN: ${{ secrets.SSC_UPLOAD_TOKEN }}
          #SSC_UPLOAD_TOKEN: 516147e5-15ee-4f01-a97a-00ab0b0a589d
          APPLICATION: "simplisticrabbitmq_sc"
          VERSION: "3.0"
          BUILD_OPTS: "-bt mvn"
